name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ] # Only run this when code is pushed to 'main'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1
  REPO_NAME: my-ml-models
  IMAGE_NAME: recruitment-api


jobs:
  # JOB 1: Continuous Integration (Test)
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_api
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Run Tests
        run: pytest

  # JOB 2: Continuous Deployment (Build & Push)
  deploy:
    needs: test # Only run if 'test' passes!
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_api
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Auth with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }} .
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy recruitment-service \
            --image europe-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --memory 2Gi